**********************************************************************************************************
********TESTE DE REGRESSÃO SIMPLES ENTRE LEGNE E ANO *************
**********************************************************************************************************

clear
use "C:\Users\Regis\Documents\GitHub\teseLegibildiadeCPC\scripts Stata\Atual\Diff Media\serie.dta"

tsset Ano
twoway (scatter LegNE Ano) (lfit LegNE Ano)
 
** correlação de person **
corr LegNE Ano

reg LegNE Ano



* Example generated by -dataex-. To install: ssc install dataex
clear
input int(Ano LegNE)
2010 27.75
2011 28.55
2012 28.59
2013 28.67
2014 28.72
2015 28.61
2016 29.33
2017 29.81
end

ktau Ano LegNE


histogram LegNE, norm 
kdensity LegNE, norm 
